
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./ip_addresses.csv:/app/ip_addresses.csv
    environment:
      - FLASK_ENV=development
      - CSV_PATH=/app/ip_addresses.csv
    command: ["python", "backend.py"]

  sender:
    build: .
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - CSV_PATH=/app/ip_addresses.csv
      - BACKEND_URL=http://backend:5000
    command: ["python", "sender.py"]